### ISSUE TITLE
ralo's docs -> prepare

### ISSUE THREAD

**Issue by uzurpastor** [uzurpastor/domino#16]
- потрібно скачати щось накшталт шаблону виконаних задач і його підзаповнити та скинути сюди (я скину йому) (шаблон лежить десь в гуглклассі)
- - потрібно сформувати тему (типу «реалізація якоїсь бізнес логіки», «проектування чогось там»)
- - потрібно сформувати 4 задачі  (типу «комунікація з тими то й тими» «реалізація алгоритму такого то» «проектування тогото» «тестування чогось» і тп
- - https://classroom.google.com/u/0/c/NTUyNDA2NzAwMTYz/a/NTU1OTUwODg0MDEz/details

- відмітити 
- - https://classroom.google.com/u/0/c/NTUyNDA2NzAwMTYz/a/NTU1OTUwNjg3NDU2/details
- - https://classroom.google.com/u/0/c/NTUyNDA2NzAwMTYz/a/NDkwNzQ0NDUzNjkw/details
Вище описані задачі які повинні виконати всі в відностно автономно, та теми з задачами скинути мені завтра до 3х годин.

**Comment by ghost** [comment]
**_Тема:_** "Реалізація бізнес-логіки гри"
**_Задачі:_**
1) Визначення бізнес-задач;
2) Проектування RESTful АРІ серверу
3) Маршутизація запитів
4) Написання логіки гри;

**Comment by LaskaAndrey** [comment]
Тема: "Проектування структури гри"
Задачі:

Визначення бізнес-задач;
1. Створення Технічного завдання для гри;
2. Означення основних правил та принципів роботи програми;
3. Створення UML діаграм, на яких зображено логіка гри та алгоритми виконання;
4.  Опис логіки бота;

**Comment by MaxPyvovarov** [comment]
**Тема:** _"Реалізація WS спілкування по мережі інтернет"_
**Задачі:**

1. Реалізація механізму гри
2. Реалізація механізму сповіщень
3. Проектування структур данних для спілкування між серверами
4. Тестування на валідність переданих данних

**Comment by uzurpastor** [comment]
@PtashkinOleg 
Тема : Проектування та розробка логіки гри 
Задачі : 
- визначення задачі та вимог  
- проектування логіки гри
- реалізація логіки гри та бота
- тестування

**Comment by uzurpastor** [comment]
@013g
**Тема:** _"Реалізація UI гри"_
**Задачі:**

1. Створення структури UI компонентів;
2. Реалізація та оптимізація UI компонентів;
3. Створення і реалізація алгоритмів роботи UI компонентів;
4. Тестування UI компонентів.

**Comment by uzurpastor** [comment]
@uzurpastor 
**Тема:** _"Докеризація проекту. Консультація інших учасників проекту"_
**Задачі:**

1. Визначення технічного стеку
2. Докеризування проекту 
3. Проксування клієнту
4. Визначення та встановлення потрібних HTTP заголовків
